language: ruby

sudo: false

cache: bundler

rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-9.1.2.0

before_script:
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"

script:
  - bundle exec rspec
  # Skip Overcommit on JRuby since it's unstable and doesn't actually test Overcommit
  - '[[ $TRAVIS_RUBY_VERSION =~ ^jruby ]] && exit || true'
  - bundle exec overcommit --sign
  - bundle exec overcommit --sign pre-commit
  - bundle exec overcommit --run
